[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  base = "."
  command = "npm run build"
  publish = "dist"
  functions = "functions"  # Se usar Netlify Functions

[dev]
  command = "npm run dev"
  targetPort = 5173  # Porta do Vite
  publish = "dist"
