git add netlify.toml
git commit -m "Corrige configuração do Netlify"
git push origin main
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [build]
  base = "frontend"  # Mas a pasta real se chama "src" ou "app"
[build]
  base = "src"
  command = "npm run build"
  publish = "dist"
[build]
  base = "."
  command = "npm run build"
  publish = "dist"
  functions = "functions"  # Se usar Netlify Functions

[dev]
  command = "npm run dev"
  targetPort = 5173  # Porta do Vite
  publish = "dist"
  "scripts": {
  "dev": "vite",
  "build": "vite build",
  "preview": "vite preview"
}
