[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
base = "caminho/para/seu/frontend"
command = "cd caminho/para/seu/frontend && npm run build"
publish = "caminho/para/seu/frontend/dist"
