[build]
  base = "src"                 # Pasta do código-fonte
  command = "npm run build"    # Comando de build correto
  publish = "dist"             # Pasta de output
  functions = "functions"      # Pasta para Netlify Functions (opcional)

[dev]
  command = "npm run dev"      # Comando para desenvolvimento
  targetPort = 5173            # Porta do Vite (ajuste se necessário)
